// creating an array and passing the number, questions, options, and answers
let questions = [
    {
    numb: 1,
    question: "EL FETO Y LA PLACENTA CONSTITUYEN UNA UNIDAD FUNCIONAL Y SU MADURACION SE HACE SINCRONICA, CONSTITUYENDO:",
    answer: "LA UNIDAD FETO PLACENTARIA",
    options: [
      "EL BINOMIO MADRE NIÑO",
      "LA UNIDAD FETO MATERNA",
      "LA UNIDAD FETO PLACENTARIA",
      "LA UNIDAD BASAL",
      "LA MADURACIÓN PLACENTARIA"
    ]
  },
    {
    numb: 2,
    question: "SON SIGNOS DE ENVEJECIMIENTO EN LA PLACENTA, CUANDO EN LA CARA MATERNA SE OBSERVAN:",
    answer: "FIBROSIS Y DEPÓSITOS DE CALCIO",
    options: [
      "FIBROSIS Y DEPÓSITOS DE CALCIO",
      "NÓDULOS BLANQUESINOS",
      "ESCLEROSIS",
      "IRREGULARIDADES"
    ]
  },
    {
    numb: 3,
    question: "EL DESARROLLO DEL PRODUCTO DE LA CONCEPCIÓN DURANTE EL PERÍODO OVULAR EN LA PRIMERA SEMANA EVOLUCIONA, HASTA:",
    answer: "BLASTOCISTO",
    options: [
      "MÓRULA",
      "BLASTOCISTO",
      "OÓTIDE",
      "CIGOTE"
    ]
  },
    {
    numb: 4,
    question: "LOS ESTRÓGENOS CUMPLEN IMPORTANTES FUNCIONES EN LA MUJER, SIENDO UNA DE ELLAS:",
    answer: "MANTENER LOS CARACTERES SEXUALES FEMENINOS",
    options: [
      "PRODUCE SEDACIÓN Y REPOSO EN EL MIOMETRIO",
      "DISMIMUYE LA SECRECIÓN DEL MOCO CERVICAL",
      "TIENE ACCIÓN HIPERTERMIZANTE",
      "MANTENER LOS CARACTERES SEXUALES FEMENINOS"
    ]
  },
    {
    numb: 5,
    question: "EL TIEMPO PARA LA CAPACITACIÓN DEL ESPERMATOZOIDE DENTRO DEL TRACTO GENITAL FEMENINO PARA ADQUIRIR EL PODER FECUNDANTE SOBRE EL ÓVULO, ES APROXIMADAMENTE:",
    answer: "SIETE HORAS",
    options: [
      "TRES HORAS",
      "SIETE HORAS",
      "DIEZ HORAS",
      "OCHO HORAS"
    ]
  },
 
  {
    numb: 6,
    question: "ENTRE LA FECUNDACIÓN Y LA ANIDACIÓN, EL TIEMPO QUE TRANSCURRE, ES:",
    answer: "SIETE DÍAS",
    options: [
      "DOS DÍAS",
      "SIETE DÍAS",
      "DIEZ DÍAS",
      "78 HORAS"
    ]
  },
  {
    numb: 7,
    question: "LA CONCEPCIÓN SUPONE TRES MOMENTOS DIFERENTES A CUMPLIRSE EN UN TIEMPO, LA SECUENCIA ES:",
    answer: "COHABITACIÓN, IMPREGNACIÓN Y CONJUGACIÓN",
    options: [
      "CONJUNGACIÓN, IMPREGNACIÓN Y FUSION",
      "COHABITACIÓN, IMPREGNACIÓN Y CONJUGACIÓN",
      "FECUNDACION, COHABITACIÓN Y CONJUGACIÓN",
      "CONJUGACIÓN, COHABITACIÓN Y FUSIÓN"
    ]
  },
  {
    numb: 8,
    question: "LA HIPOFISIS ES UNA GLÁNDULA:",
    answer: "ENDOCRINA",
    options: [
      "PANCRETICA",
      "HEPÁTICA",
      "RENAL",
      "ENDOCRINA"
    ]
  },
  {
    numb: 9,
    question: "LA ANTICONCEPCIÓN DE EMERGENCIA, ES EFICAZ SI SE ADMINISTRA DENTRO DE LAS:",
    answer: "72 HORAS DEL COITO",
    options: [
      "24 HORAS DEL COITO",
      "36 HORAS DEL COITO",
      "48 HORAS DEL COITO",
      "72 HORAS DEL COITO"
    ]
  },

  {
    numb: 10,
    question: "LA ESTERILIZACIÓN TUBARIA ESTÁ CONTRAINDICADA EN MUJERES AFECTADAS DE DIABETES O ENFERMEDAD CARDIOVASCULAR, IGUALMENTE EN:",
    answer: "OBESAS Y DESNUTRICIÓN SEVERA",
    options: [
      "EMBARAZO DE ALTO RIEGO",
      "OBESAS Y DESNUTRICIÓN SEVERA",
      "TERCIGESTAS",
      "INTOLERANCIA PARA SEGUIR OTROS MÉTODOS"
    ]
  },
  {
    numb: 11,
    question: "LA T DE COBRE 380 A ESTA HECHA DE POLIETILENO CON:",
    answer: "SULTATO DE BARIO",
    options: [
      "SULFATO DE MAGNESIO",
      "SULFATO DE SODIO",
      "SULFATO DE MANGANESO",
      "SULTATO DE BARIO"
    ]
  },
  {
    numb: 12,
    question: "CUANDO LA INSERSIÓN DEL CORDÓN NO SE REALIZA DIRECTAMENTE SOBRE LA PLACENTA, SINO QUE LO HACE EN LAS MEMBRANAS OVULARES, ¿A QUÉ DISTOCIA POR EL CORDÓN UMBILICAL CORRESPONDE?",
    answer: "INSERSIÓN VELAMENTOSA O MEMBRANOSA",
    options: [
      "PLACENTA ÁCRETA",
      "INSERSIÓN VELAMENTOSA O MEMBRANOSA",
      "DESPRENDIMIENTO PREMATURO DE PLACENTA",
      "HEMATOMA DEL CORDÓN"
    ]
  },
  {
    numb: 13,
    question: "CONSTITUYE EL GRADO EXTREMO DE LA ENFERMEDAD HEMOLÍTICA:",
    answer: "LA HIDROPESÍA DEL RECIÉN NACIDO",
    options: [
      "LA HIDROPESÍA DEL RECIÉN NACIDO",
      "EL RETARDO DE CRECIMIENTO",
      "LA ENFERMEDAD RESPIRATORIA",
      "EL DISTRES METABOLICO"
    ]
  },
  {
    numb: 14,
    question: "LA EMBOLIA DE LÍQUIDO AMNIÓTICO SE ENCUENTRA ASOCIADA, A:",
    answer: "PARTO ACELERADO, VIOLENTO",
    options: [
      "TRABAJO DE PARTO PROLONGADO",
      "ANEMIA MEGALOBLÁSICA",
      "PARTO ACELERADO, VIOLENTO",
      "HEMORRAGIA PREPARTO"
    ]
  },
  {
    numb: 15,
    question: "LAS DISTOCIAS POR LÍQUIDO AMNIÓTICO FRECUENTEMENTE SE ACOMPAÑAN, DE:",
    answer: "MALFORMACIONES CONGÉNITAS",
    options: [
      "FETO MACROSOMICO",
      "EMBARAZO MÚLTIPLE",
      "MANIOBRAS OBSTÉTRICAS",
      "MALFORMACIONES CONGÉNITAS"
    ]
  },

  {
    numb: 16,
    question: "LA GLOBULINA ANTI RH DEBE APLICARSE EN LA CONSTETLACION RH, ES DECIR CUANDO:",
    answer: "UNA MUJER RH NEGATIVO DA A LUZ UN NINO RH POSITIVO",
    options: [
      "UNA MUJER RH POSITIVO DA A LUZ UN NINO RH NEGATIVO",
      "UNA MUJER RH NEGATIVO DA A LUZ UN NINO RH POSITIVO",
      "UNA MUJER RH NEGATIVO DA A LUZ UN NINO RH NEGATIVO",
      "UNA MUJER RH POSITIVO DA A LUZ UN NINO RH POSITIVO"
    ]
  },

  {
    numb: 17,
    question: "LA APLICACIÓN DE GLOBULINA ANTI RH DEBE HACERSE INTRAMUSCULARMENTE:",
    answer: "DENTRO DE PRIMERAS 48 HORAS QUE SIGUEN AL PARTO",
    options: [
      "DENTRO DE LOS PRIMEROS 7 DÍAS DEL PARTO",
      "DESDE EL TERCER TRIMESTRE DE GESTACIÓN",
      "DENTRO DE PRIMERAS 48 HORAS QUE SIGUEN AL PARTO",
      "PASANDO LAS 72 HORAS DESPUÉS DEL 2DO PARTO"
    ]
  },

  {
    numb: 18,
    question: "UNO DE LOS FACTORES ETIOLÓGICOS DE LA HIPOACTIVIDAD UTERINA PRIMARIA, ES:",
    answer: "MALFORMACIONES UTERINAS CONGÉNITAS",
    options: [
      "AMENAZA DE ROTURA UTERINA",
      "RESISTENCIA EN EL CANAL DEL PARTO",
      "DESPRENDIMIENTO PREMATURO DE PLACENTA",
      "MALFORMACIONES UTERINAS CONGÉNITAS"
    ]
  },

  {
    numb: 19,
    question: "DISTOCIAS DE LA CONTRACCION UTERINA. LA HIPERACTIVIDAD UTERINA PUEDE DESENCADENARSE POR MÚLTIPLES CAUSAS ENTRE LAS CUALES DESTACA:",
    answer: "RESISTENCIA EN EL CANAL DEL PARTO",
    options: [
      "RESISTENCIA EN EL CANAL DEL PARTO",
      "MACROSOMÍA FETAL",
      "ENFERMEDADES CRÓNICAS",
      "ADMINISTRACIÓN DE SEDANTES"
    ]
  },

  {
    numb: 20,
    question: "EN LOS DESGARROS DE PRIMER GRADO, SÓLO SE COMPROMETEN:",
    answer: "HORQUILLA, MUCOSA Y PIEL",
    options: [
      "PIEL Y MASAS MUSCULARES",
      "HORQUILLA, VAGINA Y PERINÉ",
      "PERINÉ, VAGINA Y MÚSCULO",
      "HORQUILLA, MUCOSA Y PIEL"
    ]
  },





];